# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(383, 442)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.expressionEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.expressionEdit.setGeometry(QtCore.QRect(110, 50, 250, 35))
        self.expressionEdit.setToolTip("")
        self.expressionEdit.setObjectName("expressionEdit")
        self.expressionLabel = QtWidgets.QLabel(self.centralwidget)
        self.expressionLabel.setEnabled(True)
        self.expressionLabel.setGeometry(QtCore.QRect(20, 60, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(9)
        self.expressionLabel.setFont(font)
        self.expressionLabel.setObjectName("expressionLabel")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(110, 100, 186, 28))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.calcButton = QtWidgets.QPushButton(self.splitter)
        self.calcButton.setObjectName("calcButton")
        self.assignButton = QtWidgets.QPushButton(self.splitter)
        self.assignButton.setObjectName("assignButton")
        self.resultLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel.setEnabled(True)
        self.resultLabel.setGeometry(QtCore.QRect(50, 150, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(9)
        self.resultLabel.setFont(font)
        self.resultLabel.setObjectName("resultLabel")
        self.resultDisplay = QtWidgets.QLineEdit(self.centralwidget)
        self.resultDisplay.setGeometry(QtCore.QRect(110, 140, 250, 35))
        self.resultDisplay.setToolTip("")
        self.resultDisplay.setReadOnly(True)
        self.resultDisplay.setClearButtonEnabled(False)
        self.resultDisplay.setObjectName("resultDisplay")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(110, 190, 250, 211))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.variablesLabel = QtWidgets.QLabel(self.splitter_2)
        self.variablesLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(9)
        self.variablesLabel.setFont(font)
        self.variablesLabel.setObjectName("variablesLabel")
        self.variablesDisplay = QtWidgets.QTextBrowser(self.splitter_2)
        self.variablesDisplay.setObjectName("variablesDisplay")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.expressionLabel.setText(_translate("MainWindow", "Expression"))
        self.calcButton.setText(_translate("MainWindow", "Calculate"))
        self.assignButton.setText(_translate("MainWindow", "Assign"))
        self.resultLabel.setText(_translate("MainWindow", "Result"))
        self.variablesLabel.setText(_translate("MainWindow", "Variables"))
